[package]
name = "Chaiculator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
rug = "1.28.0"
slint = "1.13.1"

[build-dependencies]
slint-build = "1.13.1"
